name = "cloudflare-worker-loki"
main = "src/index.js"
account_id = ""
workers_dev = true
usage_model = "unbound"
compatibility_date = "2022-08-01"
send_metrics = false

[vars]
lokiHost = "https://logs-prod-012.grafana.net/loki/api/v1/push"
